# Generated by Django 3.1.2 on 2020-10-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201009_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='instructor status'),
        ),
    ]
