# Generated by Django 3.1.2 on 2020-10-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201012_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='callsign',
        ),
    ]
