# Generated by Django 3.1.2 on 2020-10-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201015_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='callsign',
            new_name='name',
        ),
    ]
