# Generated by Django 3.1.2 on 2020-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201015_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio2',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
