# Generated by Django 3.1.2 on 2020-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201018_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_url_to_receive_donation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
