# Generated by Django 3.1.2 on 2020-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='default', max_length=511),
            preserve_default=False,
        ),
    ]
