# Generated by Django 3.1.2 on 2020-10-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201022_0029'),
        ('core', '0005_remove_video_paypal_url_to_receive_donation'),
    ]

    operations = [
    ]
