# Generated by Django 3.1.2 on 2020-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201022_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
