# Generated by Django 3.1.2 on 2020-10-23 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_video_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
