# Generated by Django 3.1.2 on 2020-10-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201022_1807'),
        ('core', '0009_auto_20201022_2141'),
    ]

    operations = [
    ]
