# Generated by Django 3.1.2 on 2020-10-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20201023_0012'),
        ('core', '0010_video_publish_date'),
    ]

    operations = [
    ]
