# Generated by Django 3.1.2 on 2020-10-23 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_merge_20201023_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liked',
        ),
        migrations.AddField(
            model_name='video',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
