# Generated by Django 3.1.2 on 2020-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20201023_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, default='img/naurto_thumbsup.jpg', null=True, upload_to='img/'),
        ),
    ]
