# Generated by Django 3.1.2 on 2020-10-24 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_remove_video_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorites_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
