# Generated by Django 3.1.2 on 2020-10-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_video_favorites_by'),
        ('core', '0012_auto_20201023_1850'),
    ]

    operations = [
    ]
