# Generated by Django 3.1.2 on 2020-10-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201024_2044'),
        ('core', '0016_auto_20201024_2050'),
    ]

    operations = [
    ]
