# Generated by Django 3.1.2 on 2020-10-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201025_2325'),
        ('core', '0017_remove_video_tags'),
    ]

    operations = [
    ]
