# Generated by Django 3.1.2 on 2020-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20201025_1950'),
        ('core', '0018_merge_20201026_0745'),
    ]

    operations = [
    ]
